app/config/FrontendAppConfig.scala, app/controllers/HelpAndContactController.scala, app/controllers/actions/AuthAction.scala, app/models/requests/AuthenticatedRequest.scala, app/utils/PortalUrlBuilder.scala, app/views/sa/how_to_pay_self_assessment.scala.html, conf/application.conf, test/controllers/HelpAndContactControllerSpec.scala, test/controllers/actions/FakeAuthAction.scala, test/utils/PortalUrlBuilderSpec.scala, test/views/sa/HowToPaySelfAssessmentViewSpec.scala
* Added SA Utr to authenticated request
* Added PortalUrlBuilder functionality to insert UTR into Url
=> BTA-407 | Added enrolment specific links to how to pay SA view

project/FrontendBuild.scala
Updated Bootstrap version and tested locally.
=> Updated Bootstrap.

conf/application.conf
Updated assets frontend to fix event tracking issues for GA. Also updated google token so you can test locally.
=> BTA-797: Update assets-frontend

app/views/main_template.scala.html
BTA-1425: Added script element in main template to test web chat broken link
=> BTA-1425: [HELP-AND-CONTACT-FRONTEND] fix broken webchat link

app/controllers/HelpAndContactController.scala, app/views/help_and_contact.scala.html, conf/messages.cy, conf/messages.en, test/controllers/HelpAndContactControllerSpec.scala, test/views/epaye/ContactHmrcAboutEpayeViewSpec.scala, test/views/helpAndContactViewSpec.scala
BTA-1457: Update ePaye help and contact
=> BTA-1457: Update ePaye help and contact

app/assets/stylesheets/helpandcontactfrontend-app.scss, app/views/help_and_contact.scala.html, conf/application.conf, conf/messages.cy, conf/messages.en, test/views/helpAndContactViewSpec.scala
BTA-1559: DEV: Update to Help & Contact for MTD
=> BTA-1559: DEV: Update to Help & Contact for MTD

app/assets/stylesheets/helpandcontactfrontend-app.scss, app/assets/stylesheets/partials/_focus.scss, app/assets/stylesheets/partials/_palette.scss
BTA-1852 : Added focus classes
=> BTA-1852 : Added focus classes

app/views/components/error_summary.scala.html, conf/messages.en, test/views/components/ErrorSummarySpec.scala
BTA-1862: Added role to error summary
=> BTA-1862: Added role to error summary

it/routes/transcripts/SelfEmployedExpensesPageISpec.scala
BTA-1958 : Fixed integration test
=> BTA-1958 : Fixed integration test

app/views/sa/expenses.scala.html, it/routes/transcripts/CalculatingMotoringExpensesPageISpec.scala
BTA-1959 : Fixed unit and integration test
=> BTA-1959 : Fixed unit and integration test

app/views/govuk_wrapper.scala.html, conf/messages.cy, conf/messages.en
BTA-1871 - Added region to language switcher
=> BTA-1871 - Added region to language switcher

app/views/components/error_summary.scala.html
BTA-1910: Removed unused role from list
=> BTA-1910: Removed unused role from list

app/assets/javascripts/error_summary_focus.js, app/views/components/error_summary.scala.html, app/views/govuk_wrapper.scala.html, test/views/components/ErrorSummarySpec.scala
BTA-1863 : Added focus class when there is an error
=> BTA-1863 : Added focus class when there is an error

app/assets/stylesheets/helpandcontactfrontend-app.scss, app/views/main_template.scala.html
BTA-1918: Added polyfill js for summary tag
=> BTA-1918: Added polyfill js for summary tag

app/views/help_and_contact.scala.html, conf/application.conf, conf/messages.cy, conf/messages.en, test/views/helpAndContactViewSpec.scala, test/views/vat/registerDeregisterForVatViewSpec.scala
BTA-1996 : Added correction link
=> BTA-1996 : Added correction link

app/views/components/embed_youtube_video.scala.html, app/views/sa/expenses.scala.html, app/views/sa/help_with_your_self_assessment_tax_return.scala.html, app/views/sa/how_to_pay_self_assessment.scala.html, app/views/sa/register_deregister.scala.html, conf/messages.cy, conf/messages.en
BTA-1993: Added iframe title for accessibility
=> BTA-1993: Added iframe title for accessibility

app/config/FrontendAppConfig.scala, app/controllers/TranscriptController.scala, app/utils/CascadeUpsert.scala, app/utils/UserAnswers.scala, build.sbt, project/AppDependencies.scala, project/build.properties, project/plugins.sbt, test/base/SpecBase.scala, test/connectors/MockHttpClient.scala, test/connectors/ServiceInfoPartialConnectorSpec.scala, test/controllers/HelpAndContactControllerSpec.scala, test/controllers/TranscriptControllerSpec.scala, test/controllers/actions/AuthActionSpec.scala, test/controllers/actions/FakeServiceInfoAction.scala, test/controllers/actions/mocks/MockAuth.scala, test/utils/CascadeUpsertSpec.scala, test/utils/EnumerableSpec.scala, test/utils/PortalUrlBuilderSpec.scala
Also deleted some unused code
Accompanying essential PRs:
https://github.com/hmrc/build-jobs/pull/5967
https://github.com/hmrc/service-manager-config/pull/2279
=> DL-3560: Updated sbt, scala, plugin and dependency versions

app/controllers/TranscriptController.scala, app/views/sa/expenses.scala.html, app/views/sa/help_with_your_self_assessment_tax_return.scala.html, app/views/transcripts/basic_record_keeping.scala.html, build.sbt, conf/application.conf, conf/messages.cy, conf/messages.en, project/AppDependencies.scala, project/plugins.sbt, test/views/sa/ExpensesViewSpec.scala, test/views/sa/HelpWithYourSelfAssessmentTaxReturnViewSpec.scala, test/views/transcripts/BasicRecordKeepingForTheSelfEmployedViewSpec.scala
PR for [acceptance tests](https://github.com/hmrc/business-tax-account-acceptance-tests/pull/322) needs merging first
=> DL-3095: Add new youtube video plus transcript

app/views/components/sa_calculation.scala.html, app/views/sa/expenses.scala.html, app/views/sa/help_with_your_self_assessment_tax_return.scala.html, app/views/sa/payment_and_penalties.scala.html, app/views/transcripts/expenses_if_you_are_self_employed.scala.html, app/views/transcripts/new_income_from_property.scala.html, app/views/transcripts/new_tailor_tax_return.scala.html, app/views/transcripts/new_your_first_tax_return.scala.html, app/views/transcripts/paying_your_self_assessment_tax_bill.scala.html, app/views/transcripts/viewing_your_self_assessment_calculation.scala.html, app/views/transcripts/why_sent_tax_return.scala.html, conf/messages.cy, conf/messages.en, test/views/components/SaCalculationSpec.scala, test/views/sa/HelpWithYourSelfAssessmentTaxReturnViewSpec.scala, test/views/sa/PaymentAndPenaltiesViewSpec.scala, test/views/transcripts/ExpensesIfYouAreSelfEmployedTranscriptSpec.scala, test/views/transcripts/NewIncomeFromPropertySpec.scala, test/views/transcripts/NewTailorYourTaxReturnSpec.scala, test/views/transcripts/NewYourFirstTaxReturnSpec.scala, test/views/transcripts/PayingYourSelfAssessmentTaxBillViewSpec.scala, test/views/transcripts/ViewingYourSelfAssessmentCalculationViewSpec.scala, test/views/transcripts/WhySentTaxReturnViewSpec.scala
=> DL-14773:  Video Build Improvements 

app/controllers/TranscriptController.scala, app/views/components/basic_record_keeping.scala.html, app/views/epaye/epaye_get_started.scala.html, app/views/epaye/paye_change_circumstance.scala.html, app/views/general/how_to_add_tax.scala.html, app/views/sa/expenses.scala.html, app/views/sa/payments_and_penalties.scala.html, app/views/transcripts/how_do_i_use_payroll_software.scala.html, conf/messages.cy, conf/messages.en, test/views/components/BasicRecordKeepingSpec.scala, test/views/sa/PaymentAndPenaltiesViewSpec.scala
the work done: https://docs.google.com/document/d/1nt6k3jZniaXYDscS724TgxBZssoKTw23LdRutv8x3u0/edit?tab=t.0
=> some link and text fixes

app/controllers/HelpAndContactController.scala, app/models/PageType.scala, conf/app.routes
Urls are here: https://confluence.tools.tax.service.gov.uk/display/DLS/DL-15493+-+Help+and+Contact+%3A+URL+Mapping
=> DL-15493 - add and fix some routes

app/views/epaye/epaye_get_started.scala.html, app/views/sa/expenses.scala.html, app/views/sa/help_with_sa_tax_return.scala.html, app/views/sa/payments_and_penalties.scala.html, app/views/vat/how_to_pay_vat_and_deadlines.scala.html, test/views/ctax_closing_limited_company_view_spec.scala, test/views/ctax_how_to_pay_view_spec.scala, test/views/ctax_register_add_view_spec.scala, test/views/paye_change_circumstance_view_spec.scala, test/views/paye_stop_employer_view_spec.scala, test/views/sa/ExpensesViewSpec.scala, test/views/sa/HelpWithYourSelfAssessmentTaxReturnViewSpec.scala, test/views/sa/PaymentAndPenaltiesViewSpec.scala, test/views/vat/paymentsAndDeadlinesViewSpec.scala
What has been done as part of this ticket:
=> DL-15664 removing one of the YT links
